apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noebs

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - temporal.yaml
  - migrate-job.yaml
  - api-gateway.yaml
  - identity-auth.yaml
  - card-vault.yaml
  - ebs-adapter.yaml
  - psp-webhook.yaml
  - admin-reporting.yaml
  - notification-chat.yaml
  - wallet-api.yaml
  - wallet-ledger.yaml
  - wallet-worker.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: noebs
