apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-auth
  labels:
    app.kubernetes.io/name: identity-auth
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: card-vault
  labels:
    app.kubernetes.io/name: card-vault
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-adapter
  labels:
    app.kubernetes.io/name: ebs-adapter
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: psp-webhook
  labels:
    app.kubernetes.io/name: psp-webhook
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-reporting
  labels:
    app.kubernetes.io/name: admin-reporting
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-chat
  labels:
    app.kubernetes.io/name: notification-chat
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer-beneficiary
  labels:
    app.kubernetes.io/name: consumer-beneficiary
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-api
  labels:
    app.kubernetes.io/name: wallet-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-ledger
  labels:
    app.kubernetes.io/name: wallet-ledger
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-worker
  labels:
    app.kubernetes.io/name: wallet-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-auth-migrate
  labels:
    app.kubernetes.io/name: identity-auth-migrate
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: card-vault-migrate
  labels:
    app.kubernetes.io/name: card-vault-migrate
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-adapter-migrate
  labels:
    app.kubernetes.io/name: ebs-adapter-migrate
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: psp-webhook-migrate
  labels:
    app.kubernetes.io/name: psp-webhook-migrate
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-reporting-migrate
  labels:
    app.kubernetes.io/name: admin-reporting-migrate
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-chat-migrate
  labels:
    app.kubernetes.io/name: notification-chat-migrate
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer-beneficiary-migrate
  labels:
    app.kubernetes.io/name: consumer-beneficiary-migrate
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-ledger-migrate
  labels:
    app.kubernetes.io/name: wallet-ledger-migrate
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-postgres
  labels:
    app.kubernetes.io/name: temporal-postgres
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal
  labels:
    app.kubernetes.io/name: temporal
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-ui
  labels:
    app.kubernetes.io/name: temporal-ui
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-postgres
  labels:
    app.kubernetes.io/name: keycloak-postgres
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
automountServiceAccountToken: false
