package store

import "errors"

var (
	ErrMissingStore                      = errors.New("missing wallet store")
	ErrMissingTenantID                   = errors.New("missing tenant_id")
	ErrInvalidTenantID                   = errors.New("invalid tenant_id")
	ErrMissingCurrency                   = errors.New("missing currency")
	ErrMissingOwnerType                  = errors.New("missing owner_type")
	ErrInvalidOwnerType                  = errors.New("invalid owner_type")
	ErrMissingOwnerID                    = errors.New("missing owner_id")
	ErrMissingWalletID                   = errors.New("missing wallet_id")
	ErrWalletInactive                    = errors.New("wallet not active")
	ErrInvalidUserID                     = errors.New("invalid user_id")
	ErrMissingIdempotencyKey             = errors.New("missing idempotency_key")
	ErrInvalidIdempotencyKey             = errors.New("invalid idempotency_key")
	ErrMissingReferenceType              = errors.New("missing reference_type")
	ErrMissingReferenceID                = errors.New("missing reference_id")
	ErrMissingHoldReason                 = errors.New("missing hold reason")
	ErrMissingHoldExpiry                 = errors.New("missing hold expiry")
	ErrInvalidHoldExpiry                 = errors.New("invalid hold expiry")
	ErrMissingLockToken                  = errors.New("missing lock token")
	ErrMissingLockExpiry                 = errors.New("missing lock expiry")
	ErrInvalidHoldID                     = errors.New("invalid hold id")
	ErrInvalidAmount                     = errors.New("invalid amount")
	ErrAmountOverflow                    = errors.New("amount overflow")
	ErrInvalidWalletPair                 = errors.New("invalid wallet pair")
	ErrInvalidPercentage                 = errors.New("invalid percentage")
	ErrInvalidRate                       = errors.New("invalid rate")
	ErrWalletNotFound                    = errors.New("wallet not found")
	ErrCurrencyMismatch                  = errors.New("currency mismatch")
	ErrMissingProviderCode               = errors.New("missing provider code")
	ErrMissingPSPTransactionID           = errors.New("missing psp transaction id")
	ErrMissingDepositIntentID            = errors.New("missing deposit intent id")
	ErrInvalidDepositIntentID            = errors.New("invalid deposit intent id")
	ErrDepositIntentNotFound             = errors.New("deposit intent not found")
	ErrDuplicateDepositIntent            = errors.New("deposit intent idempotency conflict")
	ErrInvalidDepositIntent              = errors.New("invalid deposit intent")
	ErrInvalidWithdrawalRequest          = errors.New("invalid withdrawal request")
	ErrMissingClientReference            = errors.New("missing client reference")
	ErrMissingAmountKind                 = errors.New("missing amount kind")
	ErrMissingAmounts                    = errors.New("missing amounts")
	ErrInvalidAmountKind                 = errors.New("invalid amount kind")
	ErrMissingFXCurrency                 = errors.New("missing fx currency")
	ErrMissingFXRate                     = errors.New("missing fx rate")
	ErrMissingDirection                  = errors.New("missing direction")
	ErrInvalidDirection                  = errors.New("invalid direction")
	ErrPSPConfigNotFound                 = errors.New("psp config not found")
	ErrPSPConfigOverrideNotFound         = errors.New("psp config override not found")
	ErrMissingTransactionType            = errors.New("missing transaction type")
	ErrMissingApprovalDecision           = errors.New("missing approval decision")
	ErrMissingApprovalReason             = errors.New("missing approval reason")
	ErrMissingApprovalTime               = errors.New("missing approved_at")
	ErrMissingApprovalTimeout            = errors.New("missing approval timeout")
	ErrInvalidApprovalTimeout            = errors.New("invalid approval timeout")
	ErrMissingApprovalPolicy             = errors.New("missing approval_required")
	ErrMissingCompletionTime             = errors.New("missing completed_at")
	ErrMissingReturnToSourcePolicy       = errors.New("missing allow_return_to_source")
	ErrMissingStatusTimeout              = errors.New("missing status timeout")
	ErrApproverIsRequester               = errors.New("approver matches requester")
	ErrApprovalRejected                  = errors.New("approval rejected")
	ErrApprovalNotRequired               = errors.New("approval not required")
	ErrDestinationNotVerified            = errors.New("destination not verified")
	ErrMissingKYCTier                    = errors.New("missing kyc tier")
	ErrMissingBaseCurrency               = errors.New("missing base currency")
	ErrMissingQuoteCurrency              = errors.New("missing quote currency")
	ErrFeeConfigNotFound                 = errors.New("fee config not found")
	ErrExchangeRateNotFound              = errors.New("exchange rate not found")
	ErrTransactionLimitNotFound          = errors.New("transaction limit not found")
	ErrTransactionLimitExceeded          = errors.New("transaction limit exceeded")
	ErrMissingLimitCommandID             = errors.New("missing transaction limit command id")
	ErrLimitReservationNotFound          = errors.New("transaction limit reservation not found")
	ErrDuplicateLimitReservation         = errors.New("duplicate transaction limit reservation")
	ErrLimitReservationReleased          = errors.New("transaction limit reservation released")
	ErrLimitReservationConsumed          = errors.New("transaction limit reservation consumed")
	ErrInvalidLimitUsage                 = errors.New("invalid transaction limit usage")
	ErrMissingOperatorID                 = errors.New("missing operator id")
	ErrMissingOperatorIssuer             = errors.New("missing operator issuer")
	ErrInvalidOperatorIssuer             = errors.New("invalid operator issuer")
	ErrMissingOperatorSubject            = errors.New("missing operator subject")
	ErrInvalidOperatorSubject            = errors.New("invalid operator subject")
	ErrOperatorIdentityNotFound          = errors.New("operator identity not found")
	ErrMissingEventType                  = errors.New("missing event type")
	ErrMissingActorType                  = errors.New("missing actor type")
	ErrMissingActorID                    = errors.New("missing actor id")
	ErrMissingAction                     = errors.New("missing action")
	ErrMissingStatus                     = errors.New("missing status")
	ErrInvalidStatus                     = errors.New("invalid status")
	ErrInvalidStatusTransition           = errors.New("invalid status transition")
	ErrMissingInteractionType            = errors.New("missing interaction type")
	ErrMissingWorkflowID                 = errors.New("missing workflow id")
	ErrInvalidWorkflowID                 = errors.New("invalid workflow id")
	ErrMissingWorkflowSignal             = errors.New("missing workflow signal")
	ErrMissingWorkflowSignalDeliveryTime = errors.New("missing workflow signal delivery time")
	ErrPSPTransactionLockLost            = errors.New("psp transaction lock lost")
	ErrMissingTransferType               = errors.New("missing transfer type")
	ErrInvalidTransferType               = errors.New("invalid transfer type")
	ErrMissingReason                     = errors.New("missing reason")
	ErrMissingProofOfPayment             = errors.New("missing proof of payment")
	ErrMissingDecision                   = errors.New("missing decision")
	ErrInvalidDecision                   = errors.New("invalid decision")
	ErrMissingDecisionKind               = errors.New("missing decision kind")
	ErrInvalidDecisionKind               = errors.New("invalid decision kind")
	ErrMissingDecisionSubject            = errors.New("missing decision subject")
	ErrWorkflowDecisionConflict          = errors.New("workflow decision conflict")
	ErrWorkflowDecisionWindowClosed      = errors.New("workflow decision window closed")
	ErrWorkflowDecisionWindowOpen        = errors.New("workflow decision window remains open")
	ErrMissingManualTransferID           = errors.New("missing manual transfer id")
	ErrMissingRequesterID                = errors.New("missing requester operator id")
	ErrMissingApproverID                 = errors.New("missing deciding operator id")
	ErrManualTransferNotFound            = errors.New("manual transfer not found")
	ErrMissingSourceType                 = errors.New("missing source type")
	ErrMissingSourceDetails              = errors.New("missing source details")
	ErrMissingFundingSourceID            = errors.New("missing funding source id")
	ErrMissingLedgerEntryID              = errors.New("missing ledger entry id")
	ErrInvalidLedgerTransactionID        = errors.New("invalid ledger transaction id")
	ErrLedgerEntryNotFound               = errors.New("ledger entry not found")
	ErrFundingSourceNotFound             = errors.New("funding source not found")
	ErrFundingSourceNotVerified          = errors.New("funding source not verified")
	ErrFundingSourceNotWithdrawable      = errors.New("funding source not withdrawable")
	ErrFundingSourceLimitExceeded        = errors.New("funding source withdrawal limit exceeded")
	ErrFundingSourceReservationNotFound  = errors.New("funding source withdrawal reservation not found")
	ErrMissingFundingSourceReservation   = errors.New("missing funding source withdrawal reservation")
	ErrDuplicateFundingSourceReservation = errors.New("duplicate funding source withdrawal reservation")
	ErrMissingDestinationID              = errors.New("missing destination id")
	ErrInvalidDestinationID              = errors.New("invalid destination id")
	ErrMissingDestinationType            = errors.New("missing destination type")
	ErrMissingDestinationDetails         = errors.New("missing destination details")
	ErrDestinationNotFound               = errors.New("destination not found")
	ErrMissingVerificationTime           = errors.New("missing verification time")
	ErrInvalidVerificationTime           = errors.New("invalid verification time")
	ErrMissingUsageTime                  = errors.New("missing usage time")
	ErrInvalidUsageTime                  = errors.New("invalid usage time")
	ErrMissingUpdatedAt                  = errors.New("missing updated_at")
	ErrMissingStartTime                  = errors.New("missing start time")
	ErrMissingEndTime                    = errors.New("missing end time")
	ErrInvalidTimeRange                  = errors.New("invalid time range")
	ErrInvalidLimit                      = errors.New("invalid limit")
	ErrInvalidOffset                     = errors.New("invalid offset")
	ErrInsufficientFunds                 = errors.New("insufficient funds")
	ErrDuplicateWallet                   = errors.New("duplicate wallet")
	ErrDuplicateTransaction              = errors.New("duplicate transaction")
	ErrMissingSettlementTransfers        = errors.New("missing settlement transfers")
	ErrInvalidSettlementTransfer         = errors.New("invalid settlement transfer")
	ErrDuplicateHold                     = errors.New("duplicate hold")
	ErrDuplicateFundingSource            = errors.New("duplicate funding source")
	ErrDuplicateFundingLink              = errors.New("duplicate funding link")
	ErrDuplicateDestinationLink          = errors.New("duplicate destination link")
	ErrDuplicateAmount                   = errors.New("duplicate amount")
	ErrDuplicateManualTransfer           = errors.New("duplicate manual transfer")
	ErrDuplicateManualApproval           = errors.New("duplicate manual transfer approval")
	ErrDuplicateP2PCommand               = errors.New("duplicate p2p command")
	ErrP2PCommandNotFound                = errors.New("p2p command not found")
	ErrMissingP2PCommand                 = errors.New("missing p2p command")
	ErrInvalidP2PCommand                 = errors.New("invalid p2p command")
	ErrMissingWorkflowRunID              = errors.New("missing workflow run id")
	ErrInvalidWorkflowRunID              = errors.New("invalid workflow run id")
	ErrHoldNotFound                      = errors.New("hold not found")
	ErrHoldNotActive                     = errors.New("hold not active")
	ErrHoldExpired                       = errors.New("hold expired")
	ErrHoldWalletMismatch                = errors.New("hold wallet mismatch")
	ErrHoldAmountExceeded                = errors.New("hold amount exceeded")
	ErrSystemDebitWalletRequired         = errors.New("system debit wallet required")
	ErrPSPTransactionNotFound            = errors.New("psp transaction not found")
)

type TransactionLimitExceededError struct {
	Reason string
}

func (e TransactionLimitExceededError) Error() string {
	if e.Reason == "" {
		return ErrTransactionLimitExceeded.Error()
	}
	return ErrTransactionLimitExceeded.Error() + ": " + e.Reason
}

func (e TransactionLimitExceededError) Is(target error) bool {
	return target == ErrTransactionLimitExceeded
}
