package store

import "errors"

var (
	ErrMissingTenantID          = errors.New("missing tenant_id")
	ErrMissingCurrency          = errors.New("missing currency")
	ErrMissingOwnerType         = errors.New("missing owner_type")
	ErrMissingOwnerID           = errors.New("missing owner_id")
	ErrMissingWalletID          = errors.New("missing wallet_id")
	ErrInvalidUserID            = errors.New("invalid user_id")
	ErrMissingIdempotencyKey    = errors.New("missing idempotency_key")
	ErrMissingReferenceType     = errors.New("missing reference_type")
	ErrMissingReferenceID       = errors.New("missing reference_id")
	ErrMissingHoldReason        = errors.New("missing hold reason")
	ErrMissingHoldExpiry        = errors.New("missing hold expiry")
	ErrInvalidHoldID            = errors.New("invalid hold id")
	ErrInvalidAmount            = errors.New("invalid amount")
	ErrInvalidWalletPair        = errors.New("invalid wallet pair")
	ErrWalletNotFound           = errors.New("wallet not found")
	ErrCurrencyMismatch         = errors.New("currency mismatch")
	ErrMissingProviderCode      = errors.New("missing provider code")
	ErrPSPConfigNotFound        = errors.New("psp config not found")
	ErrMissingTransactionType   = errors.New("missing transaction type")
	ErrMissingKYCTier           = errors.New("missing kyc tier")
	ErrMissingBaseCurrency      = errors.New("missing base currency")
	ErrMissingQuoteCurrency     = errors.New("missing quote currency")
	ErrFeeConfigNotFound        = errors.New("fee config not found")
	ErrExchangeRateNotFound     = errors.New("exchange rate not found")
	ErrTransactionLimitNotFound = errors.New("transaction limit not found")
	ErrMissingRoleName          = errors.New("missing role name")
	ErrMissingAdminEmail        = errors.New("missing admin email")
	ErrAdminRoleNotFound        = errors.New("admin role not found")
	ErrAdminUserNotFound        = errors.New("admin user not found")
	ErrMissingEventType         = errors.New("missing event type")
	ErrMissingActorType         = errors.New("missing actor type")
	ErrMissingActorID           = errors.New("missing actor id")
	ErrMissingAction            = errors.New("missing action")
	ErrMissingStatus            = errors.New("missing status")
	ErrMissingWorkflowID        = errors.New("missing workflow id")
	ErrMissingTransferType      = errors.New("missing transfer type")
	ErrMissingReason            = errors.New("missing reason")
	ErrMissingDecision          = errors.New("missing decision")
	ErrMissingManualTransferID  = errors.New("missing manual transfer id")
	ErrMissingApproverID        = errors.New("missing approver id")
	ErrManualTransferNotFound   = errors.New("manual transfer not found")
	ErrMissingSourceType        = errors.New("missing source type")
	ErrMissingFundingSourceID   = errors.New("missing funding source id")
	ErrMissingLedgerEntryID     = errors.New("missing ledger entry id")
	ErrFundingSourceNotFound    = errors.New("funding source not found")
	ErrInsufficientFunds        = errors.New("insufficient funds")
	ErrDuplicateTransaction     = errors.New("duplicate transaction")
	ErrDuplicateHold            = errors.New("duplicate hold")
	ErrHoldNotFound             = errors.New("hold not found")
)
