apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge
resources:
  - ../../edge
configMapGenerator:
  - name: caddy-config
    behavior: replace
    files: [Caddyfile]
patches:
  - target: {kind: Deployment, name: caddy}
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value: {noebs.dev/role: workers}
      - op: replace
        path: /spec/template/spec/containers/0/ports
        value: [{name: http, containerPort: 8080}]
      - op: replace
        path: /spec/template/spec/volumes/2
        value: {name: data, emptyDir: {}}
      - op: replace
        path: /spec/template/spec/volumes/3
        value: {name: caddy-config-dir, emptyDir: {}}
