package store

import "errors"

var (
	ErrMissingTenantID       = errors.New("missing tenant_id")
	ErrInvalidTenantID       = errors.New("invalid tenant_id")
	ErrMissingUser           = errors.New("missing user")
	ErrMissingToken          = errors.New("missing token")
	ErrMissingPushData       = errors.New("missing push data")
	ErrMissingPushTarget     = errors.New("missing push target")
	ErrMissingKYC            = errors.New("missing kyc")
	ErrMissingAccount        = errors.New("missing auth account")
	ErrMissingUUID           = errors.New("missing uuid")
	ErrMissingMobile         = errors.New("missing mobile")
	ErrInvalidMobile         = errors.New("invalid mobile")
	ErrMissingPAN            = errors.New("missing pan")
	ErrMissingBillerID       = errors.New("missing biller_id")
	ErrMissingData           = errors.New("missing data")
	ErrMissingLanguage       = errors.New("missing language")
	ErrMissingPassword       = errors.New("missing password")
	ErrMissingBillType       = errors.New("missing bill_type")
	ErrMissingEmail          = errors.New("missing email")
	ErrMissingUsername       = errors.New("missing username")
	ErrMissingUserIdentifier = errors.New("missing user identifier")
	ErrMissingAPIKey         = errors.New("missing api_key")
	ErrMissingEventID        = errors.New("missing event id")
	ErrMissingEventKey       = errors.New("missing event key")
	ErrMissingEventTopic     = errors.New("missing event topic")
	ErrMissingEventType      = errors.New("missing event type")
	ErrMissingEventPayload   = errors.New("missing event payload")
	ErrMissingProvider       = errors.New("missing provider")
	ErrMissingProviderUserID = errors.New("missing provider_user_id")
	ErrInvalidUserID         = errors.New("invalid user_id")
	ErrInvalidAmount         = errors.New("invalid amount")
	ErrDuplicateAuthAccount  = errors.New("duplicate auth account")
	ErrDuplicateTransaction  = errors.New("duplicate transaction")
	ErrInvalidCardID         = errors.New("invalid card_id")
	ErrInvalidUserColumn     = errors.New("invalid user column")
	ErrMissingDataKey        = errors.New("missing data_key")
)
