package store

import "errors"

var (
	ErrMissingTenantID          = errors.New("missing tenant_id")
	ErrInvalidTenantID          = errors.New("invalid tenant_id")
	ErrTenantCatalogMismatch    = errors.New("tenant catalog does not match database")
	ErrMissingIssuer            = errors.New("missing issuer")
	ErrInvalidIssuer            = errors.New("invalid issuer")
	ErrMissingSubject           = errors.New("missing subject")
	ErrInvalidSubject           = errors.New("invalid subject")
	ErrMissingProfileName       = errors.New("missing profile fullname")
	ErrInvalidProfileName       = errors.New("invalid profile fullname")
	ErrProfileAlreadyExists     = errors.New("profile projection already exists")
	ErrProfileContactConflict   = errors.New("profile contact already exists")
	ErrMissingDeviceToken       = errors.New("missing device token")
	ErrMissingPushData          = errors.New("missing push data")
	ErrMissingPushTarget        = errors.New("missing push target")
	ErrMissingUUID              = errors.New("missing uuid")
	ErrInvalidTransactionUUID   = errors.New("invalid_transaction_uuid")
	ErrMissingMobile            = errors.New("missing mobile")
	ErrInvalidMobile            = errors.New("invalid mobile")
	ErrMissingPAN               = errors.New("missing pan")
	ErrMissingBillerID          = errors.New("missing biller_id")
	ErrMissingData              = errors.New("missing data")
	ErrMissingLanguage          = errors.New("missing language")
	ErrMissingBillType          = errors.New("missing bill_type")
	ErrMissingEventID           = errors.New("missing event id")
	ErrMissingEventKey          = errors.New("missing event key")
	ErrMissingEventTopic        = errors.New("missing event topic")
	ErrMissingEventType         = errors.New("missing event type")
	ErrMissingEventPayload      = errors.New("missing event payload")
	ErrInvalidUserID            = errors.New("invalid user_id")
	ErrDuplicateTransaction     = errors.New("duplicate transaction")
	ErrDuplicateParticipant     = errors.New("duplicate transaction participant")
	ErrInvalidParticipantRole   = errors.New("invalid transaction participant role")
	ErrInvalidCardID            = errors.New("invalid card_id")
	ErrMissingCardID            = errors.New("missing card_id")
	ErrCardNotFound             = errors.New("card_not_found")
	ErrCardEnrollmentConflict   = errors.New("card_enrollment_conflict")
	ErrEnrollmentIntentOpen     = errors.New("enrollment_intent_open")
	ErrEnrollmentIntentNotFound = errors.New("enrollment_intent_not_found")
	ErrEnrollmentIntentExpired  = errors.New("enrollment_intent_expired")
	ErrEnrollmentIntentConsumed = errors.New("enrollment_intent_consumed")
	ErrEnrollmentClaimMismatch  = errors.New("enrollment_claim_mismatch")
	ErrInvalidEnrollmentIntent  = errors.New("invalid_enrollment_intent")
	ErrInvalidCardStatus        = errors.New("invalid_card_status")
	ErrMissingRailUUID          = errors.New("missing_rail_uuid")
	ErrInvalidRailUUID          = errors.New("invalid_rail_uuid")
	ErrInvalidCardExpiry        = errors.New("invalid_card_expiry")
	ErrInvalidFundedPurpose     = errors.New("invalid_funded_operation_purpose")
	ErrInvalidFundedBodyClaim   = errors.New("invalid_funded_operation_body_claim")
	ErrFundedClaimMismatch      = errors.New("funded_operation_claim_mismatch")
	ErrInvalidRailTranDateTime  = errors.New("invalid_rail_tran_date_time")
	ErrMissingDataKey           = errors.New("missing data_key")
)
