admin_password: ENC[AES256_GCM,data:PLY6BzC3TTurUos6oxlU87CovW1Y4YEQNIrjdxEj0ZbewtY1stgbQHbxRKDZHoVc,iv:ku8KTjovhz9n+ctNsEiYzLvmv/eY/Rd2vodZcbfp5Uc=,tag:bO/3fN1TGoJ9azzFWl0i2g==,type:str]
mailbox_passwords:
    postmaster@noebs.sd: ENC[AES256_GCM,data:Hs+vEYPFbAuJCYWuFCSyghDrzNeynW9ggAEwHX/lmXKPvPezdYYxfuSoeGpE9aP3,iv:qf77dLMgSCQ52cuQKiW32ogdzwNONk4xyEQ6ITHqdmE=,tag:PWL5s3GjHzyaDf9u/m+r9A==,type:str]
    adonese@noebs.sd: ENC[AES256_GCM,data:loOYpfkRzDP+H33qiQQndR3cGq233pXqjmP/KuLBNCFI4Qp8SR97KW/CHdVePJx6,iv:gsCWmlZjR0rgSTjy5LNlqjaNyBISBvkXz5pHcy8lpbo=,tag:LBM6O90fRKTxee/M0aTHUg==,type:str]
    info@noebs.sd: ENC[AES256_GCM,data:GwwKGhWA+q0bsIocjusyA6Kg4/mOK52+rz+2+n1vb6w+OBwkC/YLNGIfat8VfkE2,iv:uwy3zO16LQpxWxG3f8EdAsZJBQWKKkfMAyeNwI93fRI=,tag:e2OBOF5XvDG0Ry7pXECJ6Q==,type:str]
    noreply@noebs.sd: ENC[AES256_GCM,data:QCXoLUZgjc7IRajoIo7ZEQcQf1hdDhqH9or1FtLfu6Pd2lkwGBcyOBiz4aNsm9OZ,iv:W3pzeqGONj5NVZRYNZsTWgWi4R4pfHjWAc7WdNEkLjI=,tag:TxKwNK8ssdVC6MK8QwNwIQ==,type:str]
    postmaster@adonese.sd: ENC[AES256_GCM,data:0sHR6Z3ipcKfFYGTsIBJtDvp3FVy6TTlAHoJugrURffDgRY7nD+vL7a+OclN/TAc,iv:yg9+qPgK16PbaC4TkWnSbhWvUBj55/7tCjtn8V9zTBE=,tag:+BJMWSATAgo+kjowQJvGjg==,type:str]
    adonese@adonese.sd: ENC[AES256_GCM,data:5qFKOk6kItnD3+0gtL9SRLgS8awLTE2mPJlFju/gxTCognJfAgipISPlyqp5mv+X,iv:2I1GGZYVmf7P6QUrxhLRVZiUhQ0G0y7NqxtB0kWFBVM=,tag:clKUubXEEFXTA/5j50em+g==,type:str]
    info@adonese.sd: ENC[AES256_GCM,data:2tymsaRroYhnq3XxnKde4t9OCRnuAquqY0xe18cef95Ua5mV4pJKDa0I81PVp6y4,iv:i/umf/cQivBzWIpYauTLfgV80c2ttkdq0ujkraCis34=,tag:AYnLtbD7pBScx7WSmWdklg==,type:str]
    noreply@adonese.sd: ENC[AES256_GCM,data:tKOGeaNLj2j4HWqfV4+Cwc7Eckma9hpGf6JCEPCRSOF+b9xZGhGUco+sxBEYqmEz,iv:ixQzjOulL94Pzx6uEYc5H643W+vp5PEq0sxp5mKmtMM=,tag:fw7wbQSIhNow9Xve7nDutA==,type:str]
    postmaster@2t.sd: ENC[AES256_GCM,data:tUAV5gKqbTou4WzLI24bd89By4sTC/Tx0yF4txIBMKwIL4wvXsBK6LvV9LYt7dIa,iv:Mrg5B1w+ADuWMgqP8eyPUtszQRifEiE73EcBhTwUeUI=,tag:4+auWQvAJPRv1eXEvfVvVw==,type:str]
    adonese@2t.sd: ENC[AES256_GCM,data:1EkNJPQ/389ND2fgxbRZ5af0+MSc2KGBH1HCY0kLnDUw/7MN3XyW/RAhyKejmO9K,iv:k7ER1ubDB0DJJk4nHQuSb72WUseWbHBWquGUOf2lYpQ=,tag:b2R3hxLWYnAqbesdUrc19w==,type:str]
    info@2t.sd: ENC[AES256_GCM,data:VZtnnWXE0Xf5LDQsQZBG0PHjqWhWOEuK6gHuGHaeWPmrqPZT08pNEwQwF5TXWHVR,iv:VdibMh/T56S8eHS3PSg32ZCjnD8KDhRfhBM6O9NUQVQ=,tag:eiXGDoM6Lz7pJoczIK57AA==,type:str]
    noreply@2t.sd: ENC[AES256_GCM,data:HJo+7MInDd7WJTi9ZbgBR6qHAs/1yNkGlTCc/lZaUdZSGFKXOEqHkpbdwcQuo0fx,iv:H/SNk9A8gHa48oZUQTLL30fDA6zOT0kWcf4JBwIPJUM=,tag:SdpcoCenSh6AXVkpBopoAg==,type:str]
cloudflare_api_token: ENC[AES256_GCM,data:+bD+xKkaYtvPrbwFTnXhbEciD0pePBj4VAVukvsgqr4Xn31fNcCd/uO7PRg3mNSF8/SgZOA=,iv:xRoMFE6jmlPncqM/aHeNKK6ufubf7sfUjCzR2XJqNu0=,tag:/qn1VmtgXh++ISGHUbDelg==,type:str]
webmail_des_key: ENC[AES256_GCM,data:xkniW9CgmoF+Nz2znhsEb/dPywHovrq9,iv:7gb6c70TuVkisuJBbGU3TWr2UxNSef5kqTkmKCC79Yk=,tag:FTW9BiGEOlqrEqhv27pxmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSmRjWUp1ZnlRak5zdktL
            VUtTemxYdkRpQXZuSUdGSU9KZjBmQ2NXL2pnCkZ1TE5FeTA0M1BOa1VkcGlHYWRW
            Z0Vib0ZId0U5S2RYV0ZnSWxicEhtb2sKLS0tIHVkek1LRmhiTHdiVndoTmloRmpu
            bXFGNVYxZ0dncEFycEJkYzNvZ3hEOTAK01mztL00Lgri0MhCVwpGU1i5PGEq4Apx
            +MuwrJxQqPO8+3kKih/0qoU0wXH7YSMWoPULuqhVjgg5QgtQeE3xBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmq9nl0haxetduys37jfj7ha93vee9pd7me7mtyw5ztm4n8flyrse3mwum
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRHhVV2RTWFZRSThwU3lH
            ZDk1WHlHdTNlYktLN3BPQ3pwM2FjYVBzVFJrClRGU0w4U2pXMlI0SG9BYThISnQ0
            RVJNREY3bmpUVWVCSXQ1R1B2Q3NZTm8KLS0tIGVwY3dDdSsrTHU2Zkl4dnpWV1Vr
            aXJXaklEWkxKdUREUUZNZENlR2Z5RUUKYAGDIk858YymeLzDx1fWYfq9DVyd5Y94
            EdYkug5gjuQWnrgPGyQcEahSffx6OGy0n57ZJrVjxSf/nJ0zM+E5xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1haq4w7h3xh2cm73yesfrv82drmhhdwqmykr3hccltaac582ggdhqlruhra
    lastmodified: "2026-09-13T08:39:07Z"
    mac: ENC[AES256_GCM,data:fZ+dqZZfR50zKeXDdbJYj8pG4zqtNBMeSUrQEHsuo5XvuwmwsN3B5JRFurCh7cXMKTAUpsP7WF4btzsgENMBuHpskH2b6pt2lYitcADdXCjjZFOJ7/6I5yQbLPZZLZdQ7Ux/cFbAsA++4EO71S34/ML6enNagS142IiOpIMr6hw=,iv:fesBvlBySfGsSsKO40kwuGxIZY69k9EP1ZmwsXHCOpA=,tag:o4oTaCoLcAYYOUn1B7qa/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
