admin_password: ENC[AES256_GCM,data:ziugfoJk8eJOn0gxa3MYCBqwTjMhJoafm920MKK9XdlRCuPedprbFxU7i0GVtj3W,iv:AAVVtnnHMkwGVC8yAMC1v3DpdVKODNHLLATVA/ivcR0=,tag:zqweRzudQyQlDq0YydzoBQ==,type:str]
mailbox_passwords:
    postmaster@noebs.sd: ENC[AES256_GCM,data:uJPLYGEyygfX3wqUr6gXiTqR2ZdtklbXR8frCj8lGitlogxJtlox/fRQJ44m15U6,iv:AiBYRCdoRbI9367xNBg5KpWAjMvz5CtoqCDwrePWBb4=,tag:NXdfqfZBunSrzR9fcH/ezA==,type:str]
    adonese@noebs.sd: ENC[AES256_GCM,data:wA7ntzi6mULT0dqfSVhzrpGxZWl4XWKX9EKk8W2a2XpBU4TkkkreugiD9AqUbYFd,iv:2g2FBfUJpjCJLeguVO501xFx8bU1/NRYJdqLzdbYxhE=,tag:LJ4Vkx4vu59D8Lwe8DPTUw==,type:str]
    info@noebs.sd: ENC[AES256_GCM,data:Vd3eMr8LOODMnX7ufEwn6+X8ANi7ueNzw35tL9ZhbSEQry/Q2AqP1QVqryuQJVOS,iv:F/yq4VllJubU1uQQ+DkQKiVsNbJP8KsDCJ8X2zVcTU4=,tag:ldLigSldEhqQZIStcS0EIA==,type:str]
    noreply@noebs.sd: ENC[AES256_GCM,data:zCjk+wb4bDL5PMRhpK4kRbiCiVp7gitajiB8ulWcS1i0t+Y4XWMTVUPnD9ZaqnDc,iv:3y49pUlHTsJIN3Z1IBhoak5nLsLAKKeBeRbjrUUqGts=,tag:cM5uqRx0jyuO/b1Bc1slNA==,type:str]
    postmaster@adonese.sd: ENC[AES256_GCM,data:ie+pL8iZMS1HPGTr1ckDYCicOH2snGrfI5qQ17SF66P5gKyChdV/hCb88h0ljoTA,iv:W+ZqUSCzeoYmGh+A9HbijJdyJ1JhQAtEzn+95Tkti2g=,tag:AcwnCDifwlbeAMAN1apf0g==,type:str]
    adonese@adonese.sd: ENC[AES256_GCM,data:GnZQi5lUU63Du25IfsAPSNlvyox8iPRzaX63T3kj0rknRmPlH4wQQXtMFt58tcPW,iv:ab6Z+pr7i6sc2OG2M40yiOvLI5mx1G6wEmvMeh6Bp4I=,tag:HzzuDJ6uBbOGAVbu74cHug==,type:str]
    info@adonese.sd: ENC[AES256_GCM,data:S8GafE2lymnfHFAjIKQTpMoONksi0LS75OJuRhYMj/gUTzzpsRIvFVv9/W8XET0A,iv:RAZC13yvjCWECJcGJLG5xL+cDmN7t5aIYzRO2qXn5c8=,tag:MUpSEaJqEuZUmYOOw8hUVQ==,type:str]
    noreply@adonese.sd: ENC[AES256_GCM,data:kqQTeuQEMytn098Ge5FMkGmLpSZQ9Cp7Z+XmaUHYZ1FkC5Vwu/oWYjNm3A07hh3c,iv:1VB1Z3TTiIe1jdW5RpMhgPPs9JWf8gxFxj3BpraBFxk=,tag:vJH3cuO+vqAdkYs+OFEbxw==,type:str]
    postmaster@2t.sd: ENC[AES256_GCM,data:6w9HbxdkjIxSFLYy7bfXRIwYem7fs4n8L5RZYTqi65HrOHWXxcnruw32OUyv8DDR,iv:pVrLSzL/+SXaSM2qQiBqjGJJQLQEVCMxhJZHJi9itec=,tag:b25iN41FpxvWcFWx/4nnuA==,type:str]
    adonese@2t.sd: ENC[AES256_GCM,data:UQ5bQFwgmbUq7r+8bvtH7Bs4XEUcxIvqJ6cAujFNYpe0tB/xFYHA5rgc7IhwdaSw,iv:5zSHzhCIlYpCXjrJ/6yBR2AONwZ2az7Qykio8vuP6x8=,tag:o38qX2AXNkpKib76KQirpw==,type:str]
    info@2t.sd: ENC[AES256_GCM,data:dO17BHftxl9mkDDgeOo/ZEy10d1mq0hOsBCu0DsjQYGLZn+zmEm++5RtnTEO3Cfh,iv:BcAVNrXkQ86qqiM1G85UMFzVa2x+eNk+HHWiug3DoMs=,tag:Q8F+QKMvDjLwT8J3keFmJg==,type:str]
    noreply@2t.sd: ENC[AES256_GCM,data:oNXbtUmRb4krSHCDgfYAVitzFAHkIEi1f+Nws7AzPMp8btAu849JeFPwK3VqtSLd,iv:HHDMJpJgcObeUA+ECkvxqE5RYqCGez8ZlYutCvf8WTk=,tag:f7w9/EKoSs7BM8cMI4lnJA==,type:str]
    admin@noebs.sd: ENC[AES256_GCM,data:Xx8lvehNG/+EaRaNuzPb+/kTU1JPnVztIxF8TCrin0LOm2+jnwC23TVqyw==,iv:l+7Lq7xLEWvNZS+/7KwJcqfHujKRcO+q/I0cT0xiqL8=,tag:yvB4NIPSugBti/kYIkO++A==,type:str]
cloudflare_api_token: ENC[AES256_GCM,data:IgQkq7qaJqCZxqc6CnQVJzTKTq2B1/3shyBHXFoPt28xP6ADSY/oXC9MxVo44kbm2cKYazk=,iv:IJidpzxQot2FK3o28bObCG2DenXjJ5E7qaZrGPFaJh8=,tag:xVJP0RoisXMTcS6N9Fc9sQ==,type:str]
webmail_des_key: ENC[AES256_GCM,data:9ERgNreP94bwDj16rtbjLB/nigjZz5Re,iv:DiFRnsk1nh+6VsFdi3OBf3rIhnX+vmTkS3qJxM26gSM=,tag:c2g1iYV3QERGWt0XfeGYiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MTlVZjNCSFpVaU53bWNQ
            VVFWeXFmL0dqQVpkY0NWVkxoMWlhWXRLK0dvCkw0M3c3ODF3UzdSNENqSnlOMFRl
            UWNvcG8yeCtsdUlxTVZuMFNXeERLNEEKLS0tIG1WcmczMklNWWx1dkwrR1dDUlkv
            a3R6bVZwNDMxY3NIUG5Rd3psbHNzWjgKFnRmTR/SCUmob6aASTHys3dlAW56Mqlv
            7w7LQByiXnLXsmpCxkvi591vkl5cycL8zZww29xmBOA1RpUBPson/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmq9nl0haxetduys37jfj7ha93vee9pd7me7mtyw5ztm4n8flyrse3mwum
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ1R0NDRhS0lLci9jRWhz
            WEFoMW1VNVlaUDN6KzRCUWFtRmQ1ekVPS2xNCkp5YUNlY0NlOG4xU3RSS2FCM3dI
            eit2L1k0S3BSTGdESVNsc1ZzRGhydTQKLS0tIEUrVDRrRmY2Nmk4Uko5bVU5MHh0
            dXo2SE04RWRkcmtwdzd0citWSmdHUncKugqOkZCwPVH6KyyAtcaOALU+Z2woRX5s
            M2Zy9KCgFnnzsYvrmVpc1Rp4Q2cEy1P64l7HKZCmdzBTbJtHnL0WcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1haq4w7h3xh2cm73yesfrv82drmhhdwqmykr3hccltaac582ggdhqlruhra
    lastmodified: "2026-09-13T15:43:15Z"
    mac: ENC[AES256_GCM,data:46m2zpwgdWPOW9MzRtJH/FB9xIXXRSLrQzwCQYAt87sqhobrEJ09rwVe0UDWQg3GQjB+RbXLRXmDIT8gmU/nenDGynkrgHEL1dCrAe06FoKhDKQqsEv5kj4IYn4yXYbE1IkivJpvxZKgeh7mp5gakgc4n2Dh3oul0euHOnJGS14=,iv:HPTYScK1XoqcsIzQzXTLHYmb1Pl5YtdLRSoup//CUcQ=,tag:381E6tWF6iNXooHNYDgWfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
