log:
  stdout: true
  level: info

persistence:
  numHistoryShards: 4
  defaultStore: default
  visibilityStore: visibility
  datastores:
    default:
      sql:
        pluginName: postgres12
        databaseName: temporal
        connectAddr: temporal-postgres:5432
        connectProtocol: tcp
        user: temporal
        password: __DATABASE_PASSWORD_FROM_FILE__
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: 1h
    visibility:
      sql:
        pluginName: postgres12
        databaseName: temporal_visibility
        connectAddr: temporal-postgres:5432
        connectProtocol: tcp
        user: temporal
        password: __DATABASE_PASSWORD_FROM_FILE__
        maxConns: 10
        maxIdleConns: 10
        maxConnLifetime: 1h

global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: temporal-frontend
  pprof:
    port: 0
  authorization:
    permissionsClaimName: permissions
    authorizer: ""
    claimMapper: ""

services:
  frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnIP: 0.0.0.0
      httpPort: 7243
  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnIP: 0.0.0.0
  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnIP: 0.0.0.0
  worker:
    rpc:
      grpcPort: 7239
      membershipPort: 6939
      bindOnIP: 0.0.0.0

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: active
  currentClusterName: active
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: frontend
      rpcAddress: 127.0.0.1:7233
      httpAddress: 127.0.0.1:7243

dcRedirectionPolicy:
  policy: noop

archival:
  history:
    state: enabled
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    state: enabled
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

namespaceDefaults:
  archival:
    history:
      state: disabled
      URI: file:///tmp/temporal_archival/development
    visibility:
      state: disabled
      URI: file:///tmp/temporal_vis_archival/development

dynamicConfigClient:
  filepath: /opt/temporal/config/dynamicconfig/docker.yaml
  pollInterval: 60s
