temporalGrpcAddress: temporal-frontend:7233
port: 8080
publicPath: ""
enableUi: true
bannerText: ""
cloudUi: false
defaultNamespace: default
feedbackUrl: ""
notifyOnNewVersion: false
refreshInterval: 0s
showTemporalSystemNamespace: false
disableWriteActions: false
workflowTerminateDisabled: false
workflowCancelDisabled: false
workflowSignalDisabled: false
workflowResetDisabled: false
batchActionsDisabled: false
startWorkflowDisabled: false
hideWorkflowQueryErrors: false
refreshWorkflowCountsDisabled: false
cors:
  cookieInsecure: false
  allowOrigins:
    - http://localhost:8080
tls:
  caFile: ""
  certFile: ""
  keyFile: ""
  caData: ""
  certData: ""
  keyData: ""
  enableHostVerification: false
  serverName: ""
auth:
  enabled: false
  providers: []
codec:
  endpoint: ""
  passAccessToken: false
  includeCredentials: false
forwardHeaders: []
hideLogs: false
