//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
)

type taskQueue struct {
	Name  string
	Value string
}

var queues = []taskQueue{
	{Name: "Main", Value: "wallet-main"},
	{Name: "Reconciliation", Value: "wallet-reconciliation"},
}

func main() {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen_task_queues.go; DO NOT EDIT.\n\n")
	buf.WriteString("package worker\n\n")
	buf.WriteString("type TaskQueue string\n\n")
	buf.WriteString("const (\n")
	for _, q := range queues {
		fmt.Fprintf(&buf, "\tTaskQueue%s TaskQueue = %q\n", q.Name, q.Value)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("task_queues_gen.go", formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
}
