// Code generated by gen_task_queues.go; DO NOT EDIT.

package worker

type TaskQueue string

const (
	TaskQueueMain           TaskQueue = "wallet-main"
	TaskQueueReconciliation TaskQueue = "wallet-reconciliation"
)
