apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noebs

resources:
  - job.yaml
  - ../../../keycloak-authority

labels:
  - pairs:
      app.kubernetes.io/part-of: noebs

images:
  - name: ghcr.io/noebs/noebs
    newName: ghcr.io/noebs/noebs
    digest: sha256:dee1f46c6826b741be166fcb04edb0c579af6f495db518c954e887b0bf2d806e
