apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noebs

resources:
  - job.yaml
  - ../../../keycloak-authority

labels:
  - pairs:
      app.kubernetes.io/part-of: noebs

images:
  - name: ghcr.io/noebs/noebs
    newName: ghcr.io/noebs/noebs
    digest: sha256:8976c1b82472b8f12a1b04d02a35ffef95d0f863c32e7ce644d3bb469cdd190c
