apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noebs

resources:
  - job.yaml
  - ../../../keycloak-authority

labels:
  - pairs:
      app.kubernetes.io/part-of: noebs

images:
  - name: ghcr.io/noebs/noebs
    newName: ghcr.io/noebs/noebs
    digest: sha256:42c3c3336782bad0bc70476c510b909188e11c8a424e83832dbf2b6c8b63554a
