ilp_secret: ENC[AES256_GCM,data:zIYuj7vP1TVhbVpx4m7LE0CRvu3s+sx3tMXm33z8amVgsJwTGovJBhCgs2oGfU358VL6P8lNrOg1ywLEJrbgCQ==,iv:V92+/xyfI4rAm2es6THKDk3fFuUgkBieDXtXPkd9RQM=,tag:pJ6wMAQ7l6Z/OwAKwu8WpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQVdJQnpjU2grMzdhNVFW
            Z2tPNlFKZTNYK1NPekl5T1hhd29ONG4vRTJrCnovTjc5bEEyZG1lN0dzbFh5eG9l
            dFJPUzZZanRNcEFoQTBFYjFyOUd3NncKLS0tIFVaSm5BS1VZUi8ycHcxS2ozWFVV
            ajRTbkJmVXUxTmRVSXNSQ1RmNGxIeUUKQ7esLwa88GsEz1RdKQp28yWT+iXWhx17
            XOQ6/UU7nP5IrTLSD1ygAmLsdiF7jpmCsKxZfURyImHq8ebbK4UX1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmq9nl0haxetduys37jfj7ha93vee9pd7me7mtyw5ztm4n8flyrse3mwum
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZzBabUxjVUNiN1lKaXpH
            N1I2SGJxcTVLV01EUkg1MS9rS2gramJGcVJVCm81M0JQcFUrK1pPdjYvNTRJZFF0
            SHNhQ3BPbjNESy82TnBaaTIwaDZObXcKLS0tIGNrbVFMOUtDejVCc1FaRkR1N3ls
            RFlqK2tvQW9CdlRlblVQd2NZWFVmR3cKAdM+BU3qN+iJRKRvSRev0kmJ6NeODPIu
            mEuT/g0n0t3RdNiJ/kCWJVARj6kYBsMQ1l7vFm4VeAcv4dYIn//GtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1haq4w7h3xh2cm73yesfrv82drmhhdwqmykr3hccltaac582ggdhqlruhra
    lastmodified: "2026-09-12T16:56:45Z"
    mac: ENC[AES256_GCM,data:fvzLQwg6iF5k0sHpfiemeT87x1keHcGOqqxirdTkBpekI51BknCv/0vsaBbjeudleOUFIbk2u3wu4Wo4EFrkGOepA3DSKGZZG9MvpgZ92tj4uOYwYT0B7/ZhyYZP5mLHKm0HZY1Ji19yso8Y9DVokg2IHU9rxf3It/i9a46QpRM=,iv:n8/v3rHyuNKYXBsExJsBwBUns3HfJFSScxy4AsQntnA=,tag:AqRuh1Us1Xkivspxpg0IuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
