wireguard_config: ENC[AES256_GCM,data:vh7NTK8i/A3JETZFiJmm7WvtQBbGnpAOKUwdVObJP/in1mDkPUSSpRYRb04VipyxN062Hy7ZBWo5S0d2BXmSbPKj68DKxhpMPN0iZTSQx+SaJxVg1GzGK3g9rt2biLlYhEH0V/C+jnul+9VvV97jjkfbwZoRqGOF44THSku/UyMQeJ79OE7mqOLMtEyYVsjR9GpAbJNnxGv9NA5DGRCDK7mRHO415njS8NxTsOfO2g3JnhCmfEFcS0wnkMS9VRswJcM30asf+/YhvS1Brxsy8qLf11GWQRNfOLzdd6F6OL1pT8aVvCvuyQDVAGtm6XqmdliAumc64XL5uTmQzgXAhoIYY9EfBHmb8X7PriNZrg==,iv:uR9Y/lQVs9To03CP0XNJaEYXx+GS569gAG3QINIrYa0=,tag:zfTXu3mrsjkO/Ih4gQ7zgg==,type:str]
exe_headers: ENC[AES256_GCM,data:y9IeqK7bd/x4bCnBwDbBn43HAPlE9vi0oYqTog6kZJ9/NUTmUw9EISIktd+jssB8ule92HtEijId/u7DrZwBpyK3PWTb7Bcf6N3UUFlsMdWBal4DYfXnEyPZWfUPv2Qk/zZoVxVCqKDijuOZXOPFa0y0b5oiYLIQo3M9v6CYTPw12oYWEG47f0GKuF4m21XlLqOU194+dDiuIxd+2sbYZHl4g0kE58k7bOo6GjQncx59N1PS2UeS01IvS07W9tmf7l7yULlBk43cQ3KXkVGTzLui7vzs/nyQdfylg8wRQOeYzZOB42GHXKqb1qx1kOB5537Hx1wQxv/Bm5fVcTyRsCHIOwn4dChtgeHEIb0DXf8iXMKICKZbjWDtyZM=,iv:McGx7nHPEKGW9qXohXFVgqhVYDEQGJUhT1+kPTxIpNs=,tag:azqM7nggtk6wNuQSkllLmQ==,type:str]
callback_relay_token: ENC[AES256_GCM,data:YXpFIYrlF8ioCGl/rQweReniRn30XG8A7rdRhY8KFGDS6O0ie+Ln8Axxf85iPjuoH1W/v5mzUMK/VT0Cj1/CVaM=,iv:cC6p4h7hXkMAMgLKrm6EVvzX6W3oJfsKYV13AllcZ6s=,tag:9HbiAcwL7cTXdQj6xLv+pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cEhlU1V5cDM1L0U5ejlH
            MlhFQ1FGd1VKTGxlb1V3NHZYNzBkQWQrdFRnCnB4c1EzOCt4MzVGdjI3c0t1R1hu
            Y0piL2trZXBsQVJDMVMzLzROR0ZEbzQKLS0tIEhEaE9CMzMxZk5FZldDS3MrakVD
            M1EzSDFCZGdCRGYycTR4RzRVVDExdjQKZU29eeK1lpR0/5CFaH6lOkhmb6J4r/Sr
            U6yiONONorI8Hk1UP88UvmHy4RHarpHkF403bwRPa//fOiHFRRW8qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmq9nl0haxetduys37jfj7ha93vee9pd7me7mtyw5ztm4n8flyrse3mwum
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dmYxcnByOTEyelI2Zkha
            ZjhGWGZxditlOUF2L1hSL05MNnJWcDJLNVVBClJJclUzUFRBNS83eHVMOWNCZTM0
            dWY4aUw5cUczQlhuQVhaVkxSQVhXY2sKLS0tIEwvb2h2LzdZcWMrT29KdytoaXc3
            THpIUGRxMldGVVBuUTF6Y09QSU5GNzQKOEECvi8BiDAQ8o+tBDxXpB9ns96RemoN
            3paeugB5x5Wcl0Vj3F0/yzR81cW/X+lRHlVfmLV7FL8k0+DO6a3xzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1haq4w7h3xh2cm73yesfrv82drmhhdwqmykr3hccltaac582ggdhqlruhra
    lastmodified: "2026-09-12T17:23:18Z"
    mac: ENC[AES256_GCM,data:OIC0x8QvlLEK7n/FW4ASX3y5kfY39+adHwHYCoOJ300AREq9GEKWxe+ib5nx0+p2FdLCv2MjKeAEku6O7j28qcAyG+LudjF2+EmkG8cNXfMWDPnzHF8/AhGibcNPMVEQhnQRcWI5aekylB/Z+AoSCIX1VD8yaG6SFqpZGD0g3jw=,iv:Cf+lvNwz2wv9n9gkF2n0JkTKJ/mXJkltjbdJYvO/pHU=,tag:+QphCBE4Bo9H+vLVdlDwvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
