ssh_private_key: ENC[AES256_GCM,data:59O3WKcRFQYdksHDKKBQUAid13pdGLmS2V8iKxOAKktPG1691S/TGqxMWiWF5rtUqC9SXSfO16IibcCKLbN8TDvxdRF0heR9rVptlmANCcRZW3LVlcUykslYRTNJDJTLtcvUlWIeRwRNgbe3qaryQHoeskPEp8OwW5fMjBqE6vsOhUg+fTD8k0AmPu74CTrd9Nlf5pPUlTKkm/N8NwgdqU5uXW3pTarCZ1rus8t1xAnCPyyxXYOokti2PmL0xbapN55dLcaOEI933LOPybvOpJGXKUQWayRPmLIpmcK1cnUbn8Oqrqu5Pp0Fb2FfOrXRLPUPCJ/X0bZJjNDz9+drcK5/BW4XiJqvvr8og/df+kczCtvp65mpiEN4YDnlRmu7Tsd86n36jjf5Td9dU+fzebRD3BiEIkHIK5ilJS7wt0Ajm4P+2pyOw1Q7nJ7s6g2nDkP1dJ3JjPWPm3eUoJjJnq+roJEsknX6Lf6eaaB7x5c8xtGRabdK3o+y/rMyH/8rIN8AErQ86EsoFd3xTpK0hM9x70aiTUpexOd7,iv:P66tGuuD2s9IAFD1CFwEU1WnR2CbN5hFJ3WNpFMNNMk=,tag:5AX/IXXRbQZRXbhGAA4gfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVDlBeTEyYWxYVXdMallI
            bHhxdXpNcFVaS1pqK2NkNXM2Q25DQ1BzOUJzCklEUFFRTGJCWWZBV3cyQTJ1MEEw
            b0pXS0FYNUhjdzh4S3FUZnB2NWdFVGMKLS0tIHZBSzlUaTl0UEFBdWRHQXo4MDlh
            TVFGYVpUSG50b3JkMStsNnBzRUY0Z1EKTq0xQclMmNJ7Fm4CcKdGkBgo0xWo9b19
            XjvDz7/p6ywdPQVuTfObUrVLTQ1rZd0t+22ib1UGAHW40bCuuSmJ5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmq9nl0haxetduys37jfj7ha93vee9pd7me7mtyw5ztm4n8flyrse3mwum
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRY3MrZ2UrYWVsVm5KcFln
            WjY3eXY2dHp6QjN4bXJMVE1YaUtYdjlZUHcwCkZxS3ZTY0IxaG1QTHdHN24yeFlS
            dVFpMG9WSDBxdzFmcEFodFJLdTVMc2sKLS0tIGxzNUFFQ0FHbWR0Smprc3pQeVF1
            YmV2eXF4bElOZTFFYzI3ZnZPMWJSc0UKQu8Lpod/UJTKKSUxHhH5e0xaJo1AZ7JV
            E8p9+X/bUJBE5k7bJ0/0WswbzHi010KkR1or9kSoZaagJyAVWRuHcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1haq4w7h3xh2cm73yesfrv82drmhhdwqmykr3hccltaac582ggdhqlruhra
    lastmodified: "2026-09-12T17:02:40Z"
    mac: ENC[AES256_GCM,data:79lng1ftOsTXjD0Py5nUuobcx4Su2OKCjyY0sTtDI61m6kLa9oUlb6iwdBwl0Qw8rHLX9Bcyj5CsfVESlB7dGlmzrYjtUcwPH85CciP886VgWTzNL3v0iiRcJjEt0/wDjGGgR8IAjpnqVovclOMpuwjEG0sy8iD6SlZgBWu9VDE=,iv:Uflc+ZoftTpDIAXPhjuZJqCbea7yFmTca6sni120eKM=,tag:OaP/3QT+C1DLUJqjDX2KMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
