tailscale_auth_key: ENC[AES256_GCM,data:KsVdncZawS7iB4eECORJzqYBrWmns35WA5eVtpbj4MmmxxutgL0TWz12+EQ7cs4QzNPD15iA9nEAs2FUoQ==,iv:eHHSJ0Jw1ee9W37jCh3ycAjLNhbLpdbqqoTmBuTOIaw=,tag:xvPvGfoZFeYF4QVKAh6P1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMzlXbGtpTDZuYnBhbHdV
            RVYxK3p2b1hLQmtOeHRrZEt0NUEyOG5ybkNzCkhoTXhaR2p2cUZ4SThsblBHQ0sx
            a3NwUUNoVlRnb2RuTXpLSUFFd1VTUG8KLS0tIEtRd053K0pXb2FYUFg4OThIV0s5
            VkVyQjFjbGJHL2NRSC9kaWg2aTNUOEEKZJF9WSRwSB/NbQJauFjTWVVwoNG9Wgge
            L2SH39IHigHlA9yA8H1jIv9BnJv4vVc/4I5257rxiYiJjHmHJIkJQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmq9nl0haxetduys37jfj7ha93vee9pd7me7mtyw5ztm4n8flyrse3mwum
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYjNxZXZFTTRHMnQrN3hC
            ZWJNZXRhTHQ2bUZMMW5nUnlybzFwNGNWbnhFCkNVeVlJOUdlaFphMVdQL0g0QXpx
            Y3d0QjhhcktEa3dkSEZIVGRSUXIwb00KLS0tIDc5ajZ5czFJSHNBS2F6MXBDYXVu
            d3ZTZHBDSitLWjQ2dXp4WURScnFQQjQKAV4Pz6/ERTAiZXlp/pgw0+PfEtx6agu9
            8THIosMqV0AiLXCWjPY+JjHnzoWsPPibA7Fy+D4f7GxbUbhzku0nrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1haq4w7h3xh2cm73yesfrv82drmhhdwqmykr3hccltaac582ggdhqlruhra
    lastmodified: "2026-09-12T16:52:02Z"
    mac: ENC[AES256_GCM,data:CdReLWfa6wKfAx4fyHIGVWnwEOJyEscOFnOkqflavQpzGUrPXf1aSZZPAZYdYZ6wGoBs5eEDq55boE6NcumSizuMRC7djJQoyw5be3bK/wpaLCQsILkbisJ+KByNEUDtZM5KvqdUnWo2G1I95RHFqR554MgTUJBEprq5agr2Ry0=,iv:ifAEGh58d5SuERI/7WZhCplZ+MnBVxTkHz5VU2Payx4=,tag:sj/iESymMqUT2T4MUomj/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
