apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  immutable: true

configMapGenerator:
  - name: tenant-catalog
    files:
      - tenant-catalog.yaml
  - name: keycloak-desired-state
    files:
      - keycloak-desired-state.yaml
