//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
)

var activityNames = []string{
	"ExecuteDoubleEntry",
	"ValidateDoubleEntry",
	"CreateHold",
	"ValidateHold",
	"ReleaseHold",
	"ValidateReleaseHold",
	"VerifyDeposit",
	"SendPayout",
	"GetTransactionStatus",
	"VerifyWalletPIN",
	"RecordFundingSource",
	"LinkLedgerToFundingSource",
	"ResolveWithdrawalDestination",
	"GetReturnToSourceOptions",
	"InitiateOwnershipVerification",
	"GetOwnershipVerification",
	"RecordAuditEvent",
	"CreateManualTransfer",
	"AddManualTransferApproval",
	"GetManualTransferByWorkflow",
	"CalculateFee",
	"CheckLimits",
	"ConvertCurrency",
	"ValidateP2PTransfer",
	"ValidateDeposit",
	"ValidateWithdrawal",
	"ResolvePSPDepositAmounts",
	"GetPSPTransactionByReference",
	"AddPSPTransactionAmounts",
	"ListPSPTransactionsForPolling",
	"UpdatePSPTransactionStatus",
	"TryAcquirePSPTransactionLock",
}

func main() {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen_activity_names.go; DO NOT EDIT.\n\n")
	buf.WriteString("package activity\n\n")
	buf.WriteString("type ActivityName string\n\n")
	buf.WriteString("const (\n")
	for _, name := range activityNames {
		fmt.Fprintf(&buf, "\tActivity%s ActivityName = %q\n", name, name)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("activity_names_gen.go", formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
}
