package activity

const (
	ActivityExecuteDoubleEntry            = "ExecuteDoubleEntry"
	ActivityValidateDoubleEntry           = "ValidateDoubleEntry"
	ActivityCreateHold                    = "CreateHold"
	ActivityValidateHold                  = "ValidateHold"
	ActivityReleaseHold                   = "ReleaseHold"
	ActivityValidateReleaseHold           = "ValidateReleaseHold"
	ActivityVerifyDeposit                 = "VerifyDeposit"
	ActivitySendPayout                    = "SendPayout"
	ActivityGetTransactionStatus          = "GetTransactionStatus"
	ActivityVerifyWalletPIN               = "VerifyWalletPIN"
	ActivityRecordFundingSource           = "RecordFundingSource"
	ActivityLinkLedgerToFundingSource     = "LinkLedgerToFundingSource"
	ActivityResolveWithdrawalDestination  = "ResolveWithdrawalDestination"
	ActivityGetReturnToSourceOptions      = "GetReturnToSourceOptions"
	ActivityInitiateOwnershipVerification = "InitiateOwnershipVerification"
	ActivityGetOwnershipVerification      = "GetOwnershipVerification"
	ActivityRecordAuditEvent              = "RecordAuditEvent"
	ActivityCreateManualTransfer          = "CreateManualTransfer"
	ActivityAddManualTransferApproval     = "AddManualTransferApproval"
	ActivityGetManualTransferByWorkflow   = "GetManualTransferByWorkflow"
	ActivityCalculateFee                  = "CalculateFee"
	ActivityCheckLimits                   = "CheckLimits"
	ActivityConvertCurrency               = "ConvertCurrency"
	ActivityValidateP2PTransfer           = "ValidateP2PTransfer"
)
