apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    app.kubernetes.io/name: api-gateway
spec:
  ingressClassName: traefik
  tls:
    - secretName: noebs-tls
      hosts:
        - api.noebs.sd
        - dsa.adonese.sd
  rules:
    - host: api.noebs.sd
      http:
        paths:
          - path: /psp/webhooks
            pathType: Prefix
            backend:
              service:
                name: psp-webhook
                port:
                  name: http
          - path: /ws
            pathType: Exact
            backend:
              service:
                name: notification-chat
                port:
                  name: http
          - path: /consumer/notifications
            pathType: Exact
            backend:
              service:
                name: notification-chat
                port:
                  name: http
          - path: /consumer/user/device
            pathType: Exact
            backend:
              service:
                name: notification-chat
                port:
                  name: http
          - path: /consumer/submit_contacts
            pathType: Exact
            backend:
              service:
                name: notification-chat
                port:
                  name: http
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: admin-reporting
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  name: http
    - host: dsa.adonese.sd
      http:
        paths:
          - path: /psp/webhooks
            pathType: Prefix
            backend:
              service:
                name: psp-webhook
                port:
                  name: http
          - path: /ws
            pathType: Exact
            backend:
              service:
                name: notification-chat
                port:
                  name: http
          - path: /consumer/notifications
            pathType: Exact
            backend:
              service:
                name: notification-chat
                port:
                  name: http
          - path: /consumer/user/device
            pathType: Exact
            backend:
              service:
                name: notification-chat
                port:
                  name: http
          - path: /consumer/submit_contacts
            pathType: Exact
            backend:
              service:
                name: notification-chat
                port:
                  name: http
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: admin-reporting
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  name: http
