// Code generated by MockGen. DO NOT EDIT.
// Source: temporal.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "go.temporal.io/sdk/client"
)

// MocktemporalClient is a mock of temporalClient interface.
type MocktemporalClient struct {
	ctrl     *gomock.Controller
	recorder *MocktemporalClientMockRecorder
}

// MocktemporalClientMockRecorder is the mock recorder for MocktemporalClient.
type MocktemporalClientMockRecorder struct {
	mock *MocktemporalClient
}

// NewMocktemporalClient creates a new mock instance.
func NewMocktemporalClient(ctrl *gomock.Controller) *MocktemporalClient {
	mock := &MocktemporalClient{ctrl: ctrl}
	mock.recorder = &MocktemporalClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemporalClient) EXPECT() *MocktemporalClientMockRecorder {
	return m.recorder
}

// ExecuteWorkflow mocks base method.
func (m *MocktemporalClient) ExecuteWorkflow(ctx context.Context, options client.StartWorkflowOptions, workflow interface{}, args ...interface{}) (client.WorkflowRun, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, options, workflow}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteWorkflow", varargs...)
	ret0, _ := ret[0].(client.WorkflowRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWorkflow indicates an expected call of ExecuteWorkflow.
func (mr *MocktemporalClientMockRecorder) ExecuteWorkflow(ctx, options, workflow interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, options, workflow}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWorkflow", reflect.TypeOf((*MocktemporalClient)(nil).ExecuteWorkflow), varargs...)
}

// SignalWorkflow mocks base method.
func (m *MocktemporalClient) SignalWorkflow(ctx context.Context, workflowID, runID, signalName string, arg interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalWorkflow", ctx, workflowID, runID, signalName, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalWorkflow indicates an expected call of SignalWorkflow.
func (mr *MocktemporalClientMockRecorder) SignalWorkflow(ctx, workflowID, runID, signalName, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalWorkflow", reflect.TypeOf((*MocktemporalClient)(nil).SignalWorkflow), ctx, workflowID, runID, signalName, arg)
}
