apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noebs

resources:
  - job.yaml

images:
  - name: ghcr.io/noebs/noebs
    newName: ghcr.io/noebs/noebs
    digest: sha256:c0d0c92966ee6a00048e5c5d6549d32a7a999964b82ed6e8823044a3ad001702
