apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noebs

resources:
  - job.yaml

images:
  - name: ghcr.io/noebs/noebs
    newName: ghcr.io/noebs/noebs
    digest: sha256:0e2490542446b06e16da952fdcc725da0975e31bf951f1fd43eea29e3e6f57e8
