// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/adonese/noebs/wallet/psp (interfaces: Provider)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	psp "github.com/adonese/noebs/wallet/psp"
	gomock "github.com/golang/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Code mocks base method.
func (m *MockProvider) Code() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code")
	ret0, _ := ret[0].(string)
	return ret0
}

// Code indicates an expected call of Code.
func (mr *MockProviderMockRecorder) Code() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockProvider)(nil).Code))
}

// GetTransactionStatus mocks base method.
func (m *MockProvider) GetTransactionStatus(arg0 context.Context, arg1 string) (*psp.TxStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatus", arg0, arg1)
	ret0, _ := ret[0].(*psp.TxStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionStatus indicates an expected call of GetTransactionStatus.
func (mr *MockProviderMockRecorder) GetTransactionStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatus", reflect.TypeOf((*MockProvider)(nil).GetTransactionStatus), arg0, arg1)
}

// SendPayout mocks base method.
func (m *MockProvider) SendPayout(arg0 context.Context, arg1 psp.PayoutRequest) (*psp.PayoutResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPayout", arg0, arg1)
	ret0, _ := ret[0].(*psp.PayoutResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPayout indicates an expected call of SendPayout.
func (mr *MockProviderMockRecorder) SendPayout(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPayout", reflect.TypeOf((*MockProvider)(nil).SendPayout), arg0, arg1)
}

// SupportedOperations mocks base method.
func (m *MockProvider) SupportedOperations() []psp.Operation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedOperations")
	ret0, _ := ret[0].([]psp.Operation)
	return ret0
}

// SupportedOperations indicates an expected call of SupportedOperations.
func (mr *MockProviderMockRecorder) SupportedOperations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedOperations", reflect.TypeOf((*MockProvider)(nil).SupportedOperations))
}

// VerifyDeposit mocks base method.
func (m *MockProvider) VerifyDeposit(arg0 context.Context, arg1 string) (*psp.DepositVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDeposit", arg0, arg1)
	ret0, _ := ret[0].(*psp.DepositVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyDeposit indicates an expected call of VerifyDeposit.
func (mr *MockProviderMockRecorder) VerifyDeposit(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDeposit", reflect.TypeOf((*MockProvider)(nil).VerifyDeposit), arg0, arg1)
}

// VerifyWebhook mocks base method.
func (m *MockProvider) VerifyWebhook(arg0 []byte, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhook", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyWebhook indicates an expected call of VerifyWebhook.
func (mr *MockProviderMockRecorder) VerifyWebhook(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhook", reflect.TypeOf((*MockProvider)(nil).VerifyWebhook), arg0, arg1)
}
